spring:
  profiles:
    active:
      -dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-gong-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-gong-test

#请保存为 UTF-8 格式